# Generated by Django 3.1.7 on 2021-03-29 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legislation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_title', models.CharField(default=None, max_length=220)),
                ('bill_number', models.CharField(default=None, max_length=220)),
                ('bill_heading', models.TextField()),
                ('bill_summary', models.TextField()),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('passed', models.BooleanField()),
                ('passed_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislation.bill')),
            ],
        ),
        migrations.CreateModel(
            name='BillType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(default=None, max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=50)),
                ('party_description', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepresentativeTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=50)),
                ('title_description', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(default=None, max_length=220, null=True)),
                ('section_title', models.CharField(default=None, max_length=220, null=True)),
                ('section_content', models.TextField(blank=True, null=True)),
                ('writing_score', models.IntegerField()),
                ('bipartisan_score', models.IntegerField()),
                ('popularity_score', models.IntegerField()),
                ('transparency_score', models.IntegerField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislation.bill')),
            ],
        ),
        migrations.CreateModel(
            name='SubsectionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBillAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing_score', models.IntegerField()),
                ('bipartisan_score', models.IntegerField()),
                ('popularity_score', models.IntegerField()),
                ('transparency_score', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubsectionLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislation.subsection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubsectionDisike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislation.subsection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubsectionCommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislation.subsectioncomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubsectionCommentDisike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislation.subsectioncomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subsectioncomment',
            name='comment_dislikes',
            field=models.ManyToManyField(blank=True, related_name='subsection_comment_dislike_user', through='legislation.SubsectionCommentDisike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subsectioncomment',
            name='comment_likes',
            field=models.ManyToManyField(blank=True, related_name='subsection_comment_like_user', through='legislation.SubsectionCommentLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subsectioncomment',
            name='subsection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislation.subsection'),
        ),
        migrations.AddField(
            model_name='subsectioncomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subsection',
            name='subsection_comments',
            field=models.ManyToManyField(blank=True, related_name='subsection_comment_user', through='legislation.SubsectionComment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subsection',
            name='subsection_dislikes',
            field=models.ManyToManyField(blank=True, related_name='subsection_dislike_user', through='legislation.SubsectionDisike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subsection',
            name='subsection_likes',
            field=models.ManyToManyField(blank=True, related_name='subsection_like_user', through='legislation.SubsectionLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbrev', models.CharField(max_length=50)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legislation.country')),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=50)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legislation.state')),
            ],
        ),
        migrations.CreateModel(
            name='BillLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislation.bill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislation.bill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillCommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislation.billcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillCommentDisLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislation.billcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='billcomment',
            name='comment_dislikes',
            field=models.ManyToManyField(blank=True, related_name='bill_comment_dislike_user', through='legislation.BillCommentDisLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billcomment',
            name='comment_likes',
            field=models.ManyToManyField(blank=True, related_name='bill_comment_like_user', through='legislation.BillCommentLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BillAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('writing_score', models.IntegerField()),
                ('bipartisan_score', models.IntegerField()),
                ('popularity_score', models.IntegerField()),
                ('transparency_score', models.IntegerField()),
                ('party_affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='legislation.party')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='legislation.state')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='legislation.representativetitle')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_authors',
            field=models.ManyToManyField(blank=True, related_name='bill_author', to='legislation.BillAuthor'),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_comments',
            field=models.ManyToManyField(blank=True, related_name='bill_comment_user', through='legislation.BillComment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_dislikes',
            field=models.ManyToManyField(blank=True, related_name='bill_dislike_user', through='legislation.BillDislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_likes',
            field=models.ManyToManyField(blank=True, related_name='bill_like_user', through='legislation.BillLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_subsections',
            field=models.ManyToManyField(blank=True, related_name='bill_subsections', to='legislation.Subsection'),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='legislation.billtype'),
        ),
        migrations.AddField(
            model_name='bill',
            name='user_bill_author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='legislation.userbillauthor'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.CharField(max_length=200)),
                ('street_number', models.CharField(max_length=50)),
                ('route', models.CharField(max_length=50)),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legislation.locality')),
            ],
        ),
    ]
