# Generated by Django 3.1.7 on 2021-03-21 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Legislation', '0004_address_party_representativetitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('writing_score', models.IntegerField()),
                ('bipartisan_score', models.IntegerField()),
                ('popularity_score', models.IntegerField()),
                ('transparency_score', models.IntegerField()),
                ('party_affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Legislation.party')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Legislation.state')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Legislation.representativetitle')),
            ],
        ),
    ]
