# Generated by Django 3.1.7 on 2021-03-21 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Legislation', '0006_userbillauthor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(default=None, max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_title', models.CharField(default=None, max_length=220)),
                ('bill_number', models.CharField(default=None, max_length=220)),
                ('bill_heading', models.TextField()),
                ('bill_summary', models.TextField()),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('passed', models.BooleanField()),
                ('passed_date', models.DateTimeField(blank=True, null=True)),
                ('bill_authors', models.ManyToManyField(blank=True, related_name='bill_author', to='Legislation.BillAuthor')),
                ('bill_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Legislation.billtype')),
                ('user_bill_author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Legislation.userbillauthor')),
            ],
        ),
    ]
